-- Insert flashcard sets
INSERT INTO flashcard_sets (id, name, description) VALUES
  ('a0000000-0000-0000-0000-000000000001', 'basic', 'Learn fundamental clasp commands'),
  ('a0000000-0000-0000-0000-000000000002', 'advanced', 'Master command flags and options');

-- Insert basic flashcards (29 cards)
INSERT INTO flashcards (set_id, task, answer, description, when_to_use, scenarios, order_index) VALUES
  ('a0000000-0000-0000-0000-000000000001', 'Authenticate with your Google Account', 'clasp login [options]', 'Authorizes clasp to manage your Google account''s Apps Script projects. This creates a credentials file that allows clasp to interact with your scripts.', 'Required before using any other clasp commands. Run this when you first install clasp or need to switch Google accounts.', '["First-time setup: After installing clasp globally, run this to authorize access to your Apps Script projects", "Switching accounts: Use --creds flag to manage multiple Google accounts for different client projects", "CI/CD setup: Use --no-localhost flag when setting up automated deployments on headless servers"]', 1),

  ('a0000000-0000-0000-0000-000000000001', 'Sign out from your Google Account', 'clasp logout', 'Removes the stored credentials from your local machine, terminating the current session. You''ll need to login again to use clasp commands.', 'When switching between different Google accounts, securing a shared computer, or troubleshooting authentication issues.', '["Account switching: Logging out before authenticating with a different Google account for a new project", "Security: Removing credentials from a shared development machine before stepping away", "Troubleshooting: Clearing stored credentials when experiencing permission errors or authentication issues"]', 2),

  ('a0000000-0000-0000-0000-000000000001', 'Open the OAuth 2.0 credentials setup', 'clasp open-credentials-setup', 'Opens the Google Cloud Console page where you can create OAuth 2.0 credentials needed for advanced clasp features like running functions remotely.', 'When you need to set up credentials for clasp run or want to use a custom OAuth client instead of the default one.', '["Advanced setup: Creating OAuth credentials before using ''clasp run'' to execute functions remotely", "Custom authentication: Setting up organization-specific OAuth clients for enterprise deployments", "API enablement: Accessing the console to enable additional Google APIs for your project"]', 3),

  ('a0000000-0000-0000-0000-000000000001', 'Clone an existing Apps Script project', 'clasp clone [options] [scriptId] [versionNumber]', 'Downloads an existing Apps Script project from Google Drive to your local filesystem. Creates a .clasp.json file linking your local directory to the remote project.', 'When you want to work locally on a project created in the online editor, collaborate on a shared project, or set up version control for an existing script.', '["Team collaboration: Cloning a colleague''s shared script to contribute code from your local development environment", "Local development: Moving an existing web-based script to your preferred IDE with Git version control", "Version management: Using --versionNumber to clone a specific historical version for debugging or rollback purposes"]', 4),

  ('a0000000-0000-0000-0000-000000000001', 'Create a new Apps Script project', 'clasp create [options]', 'Creates a new Apps Script project in your current directory and on Google Drive. Generates .clasp.json (with script ID) and appsscript.json (manifest) files.', 'When starting a new Apps Script project from scratch with local development in mind.', '["New standalone project: Creating a standalone script for a custom automation tool", "Container-bound script: Using --type sheets to create a script bound to a specific Google Sheet", "Add-on development: Starting a new Google Workspace add-on with --title and --type flags for proper setup"]', 5),

  ('a0000000-0000-0000-0000-000000000001', 'Push local files to the script', 'clasp push [options]', 'Uploads your local code files to Google Apps Script. This syncs your local changes to the cloud, making them available in the online editor.', 'After making local code changes that you want to deploy to the cloud version of your script.', '["Development workflow: Pushing code changes after testing locally to make them available in the script editor", "Continuous deployment: Using --watch flag to automatically push changes as you save files during development", "Force update: Using --force to overwrite cloud changes when you know your local version is correct"]', 6),

  ('a0000000-0000-0000-0000-000000000001', 'Pull script files from the cloud', 'clasp pull [options]', 'Downloads the latest version of your Apps Script project from Google Drive to your local filesystem, overwriting local files.', 'When you need to sync cloud changes made in the online editor to your local environment, or when collaborating with others.', '["Sync after web edits: Pulling changes you or a teammate made in the online Apps Script editor", "Collaboration: Retrieving updates from collaborators who pushed changes to the shared project", "Version retrieval: Using --versionNumber to pull a specific historical version for comparison or recovery"]', 7),

  ('a0000000-0000-0000-0000-000000000001', 'Create a new deployment version', 'clasp deploy [options]', 'Publishes your script as a versioned deployment that can be used as a web app, API executable, or add-on. Each deployment has a unique ID and URL.', 'When you want to create a production version of your script that end-users can access.', '["Web app release: Deploying a new version of your web application for users to access via URL", "API deployment: Creating an API executable deployment that can be called by external services", "Add-on publishing: Deploying a new version of your Workspace add-on for testing or production use"]', 8),

  ('a0000000-0000-0000-0000-000000000001', 'Delete an Apps Script project', 'clasp delete [options] [scriptId]', 'Permanently removes an Apps Script project from Google Drive. This action cannot be undone.', 'When you need to completely remove a script project that''s no longer needed.', '["Project cleanup: Removing test or prototype projects that are no longer relevant", "Resource management: Deleting duplicate or obsolete projects to keep your script library organized", "Security: Removing scripts containing sensitive code that should no longer be accessible"]', 9),

  ('a0000000-0000-0000-0000-000000000001', 'Remove a deployment version', 'clasp undeploy [options] [deploymentId]', 'Removes a specific deployment of your script, making it inaccessible to users. The script code remains, but the deployed version is retired.', 'When you need to retire an old version or remove a deployment that has critical bugs.', '["Version retirement: Undeploying old versions after all users have migrated to a newer release", "Emergency rollback: Quickly removing a buggy deployment while you fix the issues", "Deployment cleanup: Using --all flag to remove all deployments when starting fresh"]', 10),

  ('a0000000-0000-0000-0000-000000000001', 'List all deployment versions for a script', 'clasp deployments [scriptId]', 'Displays all active deployments for your script, showing deployment IDs, versions, and descriptions.', 'When you need to see what versions are currently deployed and accessible to users.', '["Version audit: Checking which versions are currently live before deploying a new update", "Deployment management: Getting deployment IDs to undeploy or redeploy specific versions", "Troubleshooting: Verifying that users are accessing the intended version of your web app"]', 11),

  ('a0000000-0000-0000-0000-000000000001', 'Update an existing deployment version', 'clasp redeploy [options] <deploymentId>', 'Updates an existing deployment to point to a new version of your code while maintaining the same deployment ID and URL.', 'When you want to update a deployed version without changing the URL that users access.', '["Seamless updates: Updating your web app without requiring users to change their bookmarked URL", "Production releases: Pushing new features to your production deployment while maintaining the same endpoint", "Bug fixes: Quickly updating a live deployment with a critical fix without deployment URL changes"]', 12),

  ('a0000000-0000-0000-0000-000000000001', 'Disable a Google API for the script', 'clasp disable-api <api>', 'Removes access to a specific Google API from your Apps Script project''s advanced services.', 'When you no longer need a particular API and want to reduce your project''s permissions.', '["Security hardening: Removing unused APIs to follow principle of least privilege", "Permission cleanup: Disabling APIs after refactoring code that no longer requires them", "Troubleshooting: Temporarily disabling an API to isolate permission or quota issues"]', 13),

  ('a0000000-0000-0000-0000-000000000001', 'Enable a Google API for the script', 'clasp enable-api <api>', 'Adds access to a specific Google API (like Drive, Gmail, Calendar) to your Apps Script project, allowing your code to use advanced API features.', 'When your script needs to use Google services beyond the basic built-in Apps Script services.', '["Advanced features: Enabling Drive API to access advanced file management features not in DriveApp", "External integrations: Enabling Admin SDK for G Suite domain management scripts", "Service expansion: Adding Calendar API when building a scheduling automation tool"]', 14),

  ('a0000000-0000-0000-0000-000000000001', 'List all available Google APIs', 'clasp list-apis', 'Shows all Google APIs that can be enabled for your Apps Script project, along with their current status (enabled/disabled).', 'When you need to discover which APIs are available or check which ones are currently enabled.', '["API discovery: Finding the exact API name needed for enable-api command", "Project audit: Reviewing which APIs are enabled to understand script dependencies", "Planning: Checking API availability before designing new script features"]', 15),

  ('a0000000-0000-0000-0000-000000000001', 'Open the Google Cloud Console for the project', 'clasp open-api-console', 'Opens the Google Cloud Platform Console for your script''s associated cloud project in your web browser.', 'When you need to manage advanced cloud settings, view API quotas, or configure OAuth consent screens.', '["Quota management: Checking API usage limits and requesting quota increases", "OAuth configuration: Setting up consent screens for add-ons or web apps with external users", "Service accounts: Creating service accounts for server-to-server authentication scenarios"]', 16),

  ('a0000000-0000-0000-0000-000000000001', 'Display the authorized Google Account email', 'clasp show-authorized-user', 'Shows which Google account is currently authenticated and being used by clasp for all operations.', 'When you need to verify which account you''re operating under, especially when managing multiple accounts.', '["Account verification: Confirming you''re using the correct account before pushing sensitive changes", "Multi-account management: Checking which account is active when switching between client projects", "Troubleshooting: Verifying authentication when experiencing permission errors"]', 17),

  ('a0000000-0000-0000-0000-000000000001', 'Show the current file status', 'clasp status', 'Displays the synchronization status between your local files and the cloud version, showing which files have been modified.', 'When you want to see what changes will be pushed before running clasp push.', '["Pre-push review: Checking which files have changed before pushing to avoid unintended updates", "Sync verification: Confirming your local and cloud versions are in sync after pulling", "Change tracking: Identifying which files were modified during a development session"]', 18),

  ('a0000000-0000-0000-0000-000000000001', 'Open the Apps Script execution logs', 'clasp open-logs', 'Opens the Stackdriver Logging page in your browser where you can view detailed execution logs for your script.', 'When you need to debug issues or view detailed execution history using the web interface.', '["Detailed debugging: Accessing the full web interface for complex log filtering and analysis", "Historical review: Viewing execution logs from several days or weeks ago", "Log export: Using the web interface to export logs for reporting or long-term storage"]', 19),

  ('a0000000-0000-0000-0000-000000000001', 'Set up StackDriver logging configuration', 'clasp setup-logs', 'Configures Stackdriver (Cloud Logging) for your script, enabling enhanced logging capabilities and log retention.', 'When you need advanced logging features beyond the basic Apps Script logs.', '["Production monitoring: Setting up enhanced logging for a production web app to track usage patterns", "Log retention: Configuring longer log retention periods for compliance or audit requirements", "Advanced debugging: Enabling detailed log levels for troubleshooting complex issues"]', 20),

  ('a0000000-0000-0000-0000-000000000001', 'Stream the script execution logs in real-time', 'clasp logs [options]', 'Streams execution logs directly to your terminal in real-time, showing console.log output and errors as they occur.', 'When debugging your script and you want to see logs without leaving the terminal.', '["Live debugging: Watching logs in real-time while testing your script''s functionality", "Error monitoring: Using --watch flag to continuously monitor for errors in a running web app", "Development workflow: Viewing console.log output while developing without switching to the browser"]', 21),

  ('a0000000-0000-0000-0000-000000000001', 'Open the Apps Script editor in browser', 'clasp open-script [scriptId]', 'Opens your Apps Script project in the online editor in your default web browser.', 'When you need to quickly access the web editor for visual editing, project settings, or features not available in clasp.', '["Visual editing: Opening the editor to use the UI builder for creating custom menus or dialogs", "Project settings: Accessing the web interface to configure triggers, libraries, or permissions", "Quick checks: Verifying how your code appears in the online editor or testing the script there"]', 22),

  ('a0000000-0000-0000-0000-000000000001', 'Open the container-bound document/sheet', 'clasp open-container', 'Opens the Google Doc, Sheet, Form, or Slides presentation that your script is bound to in your web browser.', 'When working with container-bound scripts and you need to access the parent document.', '["Sheet testing: Opening the bound spreadsheet to test custom menu items or sheet functions", "Form configuration: Accessing the form that your script processes submissions for", "Document context: Viewing the document structure while developing container-bound automation"]', 23),

  ('a0000000-0000-0000-0000-000000000001', 'Open the deployed web app in browser', 'clasp open-web-app [deploymentId]', 'Opens a specific deployment of your web app in your browser, using the deployment''s public URL.', 'When you want to quickly test or view a deployed version of your web application.', '["Deployment testing: Opening a new deployment to verify it''s working correctly before sharing with users", "Version comparison: Opening different deployment IDs to compare behavior between versions", "Quick access: Launching your web app without manually copying and pasting the deployment URL"]', 24),

  ('a0000000-0000-0000-0000-000000000001', 'Execute a function in the script', 'clasp run [options] [functionName]', 'Remotely executes a specific function in your Apps Script project directly from the command line, returning the results to your terminal.', 'When you want to test functions or run one-off scripts without manually triggering them in the editor.', '["Function testing: Running and testing individual functions during development without the web editor", "One-off tasks: Executing data migration or cleanup functions from your terminal", "CI/CD integration: Running test functions as part of automated deployment pipelines"]', 25),

  ('a0000000-0000-0000-0000-000000000001', 'List all Apps Script projects for current user', 'clasp list [options]', 'Displays all Apps Script projects accessible by your currently authenticated Google account, showing script IDs and titles.', 'When you need to find a script ID or see all your available projects.', '["Script discovery: Finding the script ID of a project you want to clone", "Project inventory: Viewing all your scripts to decide which ones to work on locally", "Account audit: Checking what script projects are associated with your Google account"]', 26),

  ('a0000000-0000-0000-0000-000000000001', 'Create a new version of the script', 'clasp version [description]', 'Creates an immutable snapshot of your current script code as a numbered version. This version can then be deployed.', 'When you want to create a stable reference point before deploying or making major changes.', '["Pre-deployment: Creating a version with a description before deploying to production", "Release tagging: Marking significant milestones like ''v2.0 - Added user authentication''", "Safe refactoring: Creating a version before major code changes so you can easily revert if needed"]', 27),

  ('a0000000-0000-0000-0000-000000000001', 'List all versions of a script project', 'clasp versions [scriptId]', 'Shows all saved versions of your script with their version numbers, descriptions, and creation dates.', 'When you need to review version history or find a specific version number for deployment or rollback.', '["Version audit: Reviewing the history of your project to understand when changes were made", "Rollback planning: Finding the version number of a stable release to redeploy", "Documentation: Getting version information for release notes or change logs"]', 28),

  ('a0000000-0000-0000-0000-000000000001', 'Start the Model Context Protocol server', 'clasp mcp', 'Starts a Model Context Protocol (MCP) server that allows AI assistants and tools to interact with your Apps Script projects through a standardized interface.', 'When you want to enable AI-assisted development or integrate your Apps Script projects with MCP-compatible tools.', '["AI development: Enabling an AI assistant like Claude to help write and modify your Apps Script code", "Tool integration: Connecting automated development tools that use the MCP protocol", "Enhanced workflows: Using MCP-compatible IDEs that provide enhanced Apps Script development features"]', 29);
